### ISSUE TITLE
Pandas >=1.3.0 breaks the code

### ISSUE THREAD

**Issue by jbusecke** [GliderToolsCommunity/GliderTools#136] opened 2021-07-22 17:26 UTC
**Describe the bug**
Our [CI](https://github.com/GliderToolsCommunity/GliderTools/actions/workflows/ci.yml) is currently broken. 

#135 seems to confirm that this is caused by recent changes in pandas. 

As a short term fix we could pin a version <1.3.0 for the CI and in our packaging. But in the long term, we should make sure that our code is compatible with the newest pandas version.

**Comment by callumrollo** [comment] 2021-11-10 17:55
I'm in the process of tracking down this bug. This appears to be the guilty line:

**utils.py line 132**
`df = df.interpolate(limit=interp_lim).bfill(limit=interp_lim)`

Specifically, the df.interpolate part. I have found a [SO question](https://stackoverflow.com/questions/58843656/pandas-interpolation-valueerrorinvalid-fill-method-expecting-pad-ffill-or) that looks like the same problem. The answer suggests that datetime columns in the dataframes may be the root cause

**Comment by soerenthomsen** [comment] 2022-12-12 14:54
@MartinMohrmann can this issue be closed?

**Comment by callumrollo** [comment] 2022-12-12 15:16
Yup. Fixed in #154

**Closed by callumrollo** 2022-12-12 15:16 UTC
